### ISSUE TITLE
Can't run rails g ember_devise_simple_auth:install with latest gem version

### ISSUE THREAD

**Issue by abuiles** [the-refinery/ember-devise-simple-auth#16] opened 2014-03-05 02:24 UTC
I keep getting `Could not find generator ember_devise_simple_auth:install.`

**Comment by cevn** [comment] 2014-03-05 04:18
Can you elaborate on this? Did you run `bundle install`? I can't seem to reproduce this issue.

**Comment by joefiorini** [comment] 2014-03-07 15:38
@cevn Which gem version are you on? I borked the directory structure in the last push and Rails can't find the generator now. This is definitely an issue, just haven't had time to fix it yet :/

**Comment by cevn** [comment] 2014-03-07 17:22
@joefiorini Oh, I was on 0.3.0, haha. That's probably why I had no problems. 

Also, I know this isn't quite the place to ask, but could you go over setting this up in a stock ember-appkit-rails and devise environment in the docs somewhere? I couldn't quite get it to work. This repository seems to be the best hope for ember auth at the moment.

**Comment by abuiles** [comment] 2014-03-08 22:19
@joefiorini noticed you started to move the bower part to other repo, are you separating the Ruby and JS stuff?

**Comment by joefiorini** [comment] 2014-03-09 02:45
No really, bower is separate because you can only register modules as git repos and it's bad practice to put built source in your main repo. Once they have a proper registry I'll delete that repository.

-- 
Joe Fiorini

On March 8, 2014 at 5:19:32 PM, Adolfo Builes (notifications@github.com) wrote:

@joefiorini noticed you started to move the bower part to other repo, are you separating the Ruby and JS stuff?

**Comment by joefiorini** [comment] 2014-03-13 18:13
I've pushed a fix for this. Should be good now.

**Closed as completed by joefiorini** 2014-03-13 18:13 UTC
